#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///

import sys

from hook_io import read_payload, run_hook, write_context

NOTES = {
    "agent-roles": (
        "Start workers as misticos agents, picked by the role in their "
        "descriptions, including workflow agents through agentType. Use a "
        "built-in agent type only when no role fits."
    ),
    "pr-body": (
        "The tool may have appended harness text to the pull request body, "
        'such as a "Generated by" footer or a session link. Read the body back '
        "now and remove that text."
    ),
}


def main():
    note = NOTES[sys.argv[1]]
    event = read_payload().get("hook_event_name")
    if event:
        write_context(event, note)


if __name__ == "__main__":
    run_hook(main)
