#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///

import json
import sys

from hook_io import hook_output, read_payload

READ_BACK_REMINDER = (
    "The tool may have appended harness text to the pull request body, such "
    'as a "Generated by" footer or a session link. Read the body back now '
    "and remove that text."
)


def main():
    payload = read_payload()
    event = payload.get("hook_event_name")
    if event:
        json.dump(hook_output(event, READ_BACK_REMINDER, "claude"), sys.stdout)


if __name__ == "__main__":
    main()
